---
apiVersion: v1
kind: Service
metadata:
  name: addr-server
  labels:
    app: addr-server
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080
    - name: grpc
      port: 30051
      nodePort: 30051
  selector:
    app: addr-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addr-server
  labels:
    app: addr-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: addr-server
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 1
  #    maxUnavailable: 1
  #  type: RollingUpdate

  template:   # pod definition
    metadata:
      labels:
        app: addr-server
    spec:
      containers:
        - name: addr-server
          image: addr-server
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: grpc
              containerPort: 30051
          readinessProbe:
             httpGet:
               path: /health
               port: 80
             #initialDelaySeconds: 20
             #periodSeconds: 10